function statecond_createfig(X1, Y1, yvector1, yvector2, yvector3)
%CREATEFIGURE(X1, Y1, YVECTOR1, YVECTOR2, YVECTOR3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  YVECTOR1:  bar yvector
%  YVECTOR2:  area yvector
%  YVECTOR3:  area yvector

%  Auto-generated by MATLAB on 07-Apr-2017 15:29:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Position',[0.13 0.767258064516129 0.775 0.157741935483871]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1,'Color',[0 0 1]);

% Create title
title('Conditioning variable y_t');

% Create ylabel
ylabel('VIX');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[730125 731941]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XTick',[730200 730600 731000 731400 731800],...
    'XTickLabel',{'Mar99','Apr00','May01','Jul02','Aug03'});
% Create subplot
subplot1 = subplot(4,1,2);
hold(subplot1,'on');

% Create bar
bar(X1,yvector1,'EdgeColor','none');

% Create title
title('Crisp state conditioned probabilities');

% Create ylabel
ylabel('Probability');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[730125 731941]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 0.005]);
box(subplot1,'on');
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',16,'XTick',[730200 730600 731000 731400 731800],...
    'XTickLabel',{'Mar99','Apr00','May01','Jul02','Aug03'});
% Create subplot
subplot2 = subplot(4,1,3);
hold(subplot2,'on');

% Create area
area(X1,yvector2,...
    'FaceColor',[0.0784313753247261 0.168627455830574 0.549019634723663]);

% Create title
title('Smooth kernel state conditioned probabilities');

% Create ylabel
ylabel('Probability');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[730125 731941]);
box(subplot2,'on');
grid(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',16,'XTick',[730200 730600 731000 731400 731800],...
    'XTickLabel',{'Mar99','Apr00','May01','Jul02','Aug03'});
% Create subplot
subplot3 = subplot(4,1,4);
hold(subplot3,'on');

% Create area
area(X1,yvector3,...
    'DisplayName','Time and state conditioned historical scenario',...
    'Parent',subplot3,...
    'FaceColor',[0.0784313753247261 0.168627455830574 0.549019634723663]);

% Create title
title('Time and state conditioned fully flexible probabilities');

% Create ylabel
ylabel('Probability');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[730125 731941]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0 0.012]);
box(subplot3,'on');
grid(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',16,'XTick',[730200 730600 731000 731400 731800],...
    'XTickLabel',{'Mar99','Apr00','May01','Jul02','Aug03'});
% Create line
annotation(figure1,'line',[0.129089301503095 0.905393457117595],...
    [0.806451612903226 0.806451612903226],'Color',[1 0 0],'LineWidth',1,...
    'LineStyle','--');

